// Generated by CoffeeScript 1.10.0
(function() {
  var Doc, Method, Mixin, Node, Variable,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Node = require('./node');

  Method = require('./method');

  Variable = require('./variable');

  Doc = require('./doc');

  module.exports = Mixin = (function(superClass) {
    extend(Mixin, superClass);

    function Mixin(node, fileName, options1, comment) {
      var doc, error, error1, exp, i, j, k, len, len1, len2, method, previousExp, ref, ref1, ref2, ref3, ref4;
      this.node = node;
      this.fileName = fileName;
      this.options = options1;
      try {
        this.methods = [];
        this.variables = [];
        this.doc = new Doc(comment, this.options);
        previousExp = null;
        ref = this.node.value.base.properties;
        for (i = 0, len = ref.length; i < len; i++) {
          exp = ref[i];
          if (exp.constructor.name === 'Assign') {
            if ((previousExp != null ? previousExp.constructor.name : void 0) === 'Comment') {
              doc = previousExp;
            }
            if (((ref1 = exp.value) != null ? ref1.constructor.name : void 0) === 'Code') {
              this.methods.push(new Method(this, exp, this.options, doc));
            }
            if (((ref2 = exp.value) != null ? ref2.constructor.name : void 0) === 'Value') {
              switch (exp.variable.base.value) {
                case 'ClassMethods':
                  this.classMixin = new Mixin(exp, this.filename, this.options, doc);
                  break;
                case 'InstanceMethods':
                  this.instanceMixin = new Mixin(exp, this.filename, options, doc);
              }
            }
          }
          doc = null;
          previousExp = exp;
        }
        if ((this.classMixin != null) && (this.instanceMixin != null)) {
          this.concern = true;
          ref3 = this.classMixin.getMethods();
          for (j = 0, len1 = ref3.length; j < len1; j++) {
            method = ref3[j];
            method.type = 'class';
            this.methods.push(method);
          }
          ref4 = this.instanceMixin.getMethods();
          for (k = 0, len2 = ref4.length; k < len2; k++) {
            method = ref4[k];
            method.type = 'instance';
            this.methods.push(method);
          }
        } else {
          this.concern = false;
        }
      } catch (error1) {
        error = error1;
        if (this.options.verbose) {
          console.warn('Create mixin error:', this.node, error);
        }
      }
    }

    Mixin.prototype.getFileName = function() {
      return this.fileName;
    };

    Mixin.prototype.getDoc = function() {
      return this.doc;
    };

    Mixin.prototype.getMixinName = function() {
      var error, error1, i, len, name, p, ref;
      try {
        if (!this.mixinName) {
          name = [];
          if (this.node.variable.base.value !== 'this') {
            name = [this.node.variable.base.value];
          }
          ref = this.node.variable.properties;
          for (i = 0, len = ref.length; i < len; i++) {
            p = ref[i];
            name.push(p.name.value);
          }
          this.mixinName = name.join('.');
        }
        return this.mixinName;
      } catch (error1) {
        error = error1;
        if (this.options.verbose) {
          return console.warn('Get mixin full name error:', this.node, error);
        }
      }
    };

    Mixin.prototype.getFullName = function() {
      return this.getMixinName();
    };

    Mixin.prototype.getName = function() {
      var error, error1;
      try {
        if (!this.name) {
          this.name = this.getMixinName().split('.').pop();
        }
        return this.name;
      } catch (error1) {
        error = error1;
        if (this.options.verbose) {
          return console.warn('Get mixin name error:', this.node, error);
        }
      }
    };

    Mixin.prototype.getNamespace = function() {
      var error, error1;
      try {
        if (!this.namespace) {
          this.namespace = this.getMixinName().split('.');
          this.namespace.pop();
          this.namespace = this.namespace.join('.');
        }
        return this.namespace;
      } catch (error1) {
        error = error1;
        if (this.options.verbose) {
          return console.warn('Get mixin namespace error:', this.node, error);
        }
      }
    };

    Mixin.prototype.getMethods = function() {
      return this.methods;
    };

    Mixin.prototype.getVariables = function() {
      return this.variables;
    };

    return Mixin;

  })(Node);

}).call(this);
